# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_message', models.TextField()),
                ('blog_date_created', models.DateTimeField(auto_now_add=True)),
                ('blog_thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('blog_slug', models.SlugField()),
                ('blog_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
